version: '3.8'

services:
  day_quote:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: day_quote
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development